Repository dubeyji0110/OpenSourceContribution, pull requests merged in 2021-10, with the labels that each got.

#7 spotify skip prediction model
  Python/Spotify Skip Prediction/spotify_skip_prediction.ipynb
Labels: hacktoberfest-accepted

#8 Added Contributors
  README.md
Labels: good first issue

#9 bfs code added
  cpp/bfs.cpp
Labels: good first issue, hacktoberfest-accepted

#10 added newton rapshon
  cpp/newtonraphson.cpp
Labels: good first issue, hacktoberfest-accepted

#13 Create BubbleSort.java
  BubbleSort.java
Labels: good first issue, hacktoberfest-accepted

#12 Tic-Tac-Toe using minimax algorithm
  Python/TicTacToe/main.py
Labels: good first issue, hacktoberfest-accepted

#14 dfs algorithm in cpp
  cpp/dfsalgo.cpp
Labels: hacktoberfest-accepted

#17 Added Fibonacci series in php
  Php/fibonacci.php
Labels: hacktoberfest-accepted

#16 Added Kadane's Algorithm in cpp
  cpp/.vscode/c_cpp_properties.json
  cpp/.vscode/launch.json
  cpp/.vscode/settings.json
  cpp/kadanealgo.cpp
Labels: hacktoberfest-accepted

#21 Added a problem of Longest Common Subsequence
  cpp/LongestCommonSubsequence.cpp
Labels: hacktoberfest-accepted

#22 add stack by LL
  cpp/StackByLinkedList.cpp
Labels: hacktoberfest-accepted

#25 Added Dijkstra's algorithm code
  cpp/dijkstra.cpp
Labels: hacktoberfest-accepted

#24 Create Break_a_Palindrome.cpp
  cpp/Break_a_Palindrome.cpp
Labels: hacktoberfest-accepted

#23 Create text_to-speech.py
  Python/text_to-speech.py
Labels: hacktoberfest-accepted

#26 Added Queue Implementation in c++
  cpp/queueUsingArray.cpp
  cpp/queueUsingLL.cpp
Labels: hacktoberfest-accepted

#27 using SUPPORT VECTOR MACHINE
  Python/Digit_Recognition.ipynb
Labels: hacktoberfest-accepted

#28 Added Dino bot game automation using python
  Python/bot.py
Labels: hacktoberfest-accepted

#29 Lexer in cpp
  .gitignore
  cpp/lexer.cpp
Labels: hacktoberfest-accepted

#40 bipartite graph program
  Bipartite.cpp
  DFS.cpp
Labels: hacktoberfest-accepted
